"""add order and relationship

Revision ID: 07840506c7ea
Revises: dc70cd732018
Create Date: 2026-01-20 11:47:20.704179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07840506c7ea'
down_revision: Union[str, Sequence[str], None] = 'dc70cd732018'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem_record', sa.Column('order', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problem_record', 'order')
    # ### end Alembic commands ###
