"""streak model add

Revision ID: 09b86e2a6522
Revises: adfb5f7c7742
Create Date: 2026-01-04 16:50:21.043106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '09b86e2a6522'
down_revision: Union[str, Sequence[str], None] = 'adfb5f7c7742'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('streak',
    sa.Column('streak_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bj_account_id', sa.String(length=50), nullable=False),
    sa.Column('streak_date', sa.Date(), nullable=False),
    sa.Column('solved_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bj_account_id'], ['bj_account.bj_account_id'], ),
    sa.PrimaryKeyConstraint('streak_id'),
    comment='스트릭 정보 (날짜별 푼 문제 수)'
    )
    op.create_index('idx_bj_account_date', 'streak', ['bj_account_id', 'streak_date'], unique=False)
    op.add_column('problem_history', sa.Column('streak_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('idx_solved_at'), table_name='problem_history')
    op.create_index('idx_bj_account_problem', 'problem_history', ['bj_account_id', 'problem_id'], unique=False)
    op.create_foreign_key(None, 'problem_history', 'streak', ['streak_id'], ['streak_id'])
    op.create_table_comment(
        'problem_history',
        '문제 해결 히스토리 (시간 정보 없음, streak과 연동)',
        existing_comment='문제 해결 히스토리',
        schema=None
    )
    op.drop_column('problem_history', 'solved_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem_history', sa.Column('solved_at', mysql.DATETIME(), nullable=True))
    op.create_table_comment(
        'problem_history',
        '문제 해결 히스토리',
        existing_comment='문제 해결 히스토리 (시간 정보 없음, streak과 연동)',
        schema=None
    )
    op.drop_constraint(None, 'problem_history', type_='foreignkey')
    op.drop_index('idx_bj_account_problem', table_name='problem_history')
    op.create_index(op.f('idx_solved_at'), 'problem_history', ['solved_at'], unique=False)
    op.drop_column('problem_history', 'streak_id')
    op.drop_index('idx_bj_account_date', table_name='streak')
    op.drop_table('streak')
    # ### end Alembic commands ###
