"""add tag_id to skill

Revision ID: 31a0fd8f1cd1
Revises: b270af27c31e
Create Date: 2026-01-13 05:35:43.014136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31a0fd8f1cd1'
down_revision: Union[str, Sequence[str], None] = 'b270af27c31e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag_skill', sa.Column('tag_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tag_skill', 'tag', ['tag_id'], ['tag_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tag_skill', type_='foreignkey')
    op.drop_column('tag_skill', 'tag_id')
    # ### end Alembic commands ###
