"""remove activity tables and user_account_id

Revision ID: 51ec33d74fa2
Revises: d3e4f5a6b7c8
Create Date: 2026-02-25 15:02:49.977518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '51ec33d74fa2'
down_revision: Union[str, Sequence[str], None] = 'd3e4f5a6b7c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('will_solve_problem')
    op.drop_table('problem_banned_record')
    op.drop_table('problem_record')
    op.drop_constraint(op.f('fk_pdr_user_account'), 'problem_date_record', type_='foreignkey')
    op.drop_column('problem_date_record', 'user_account_id')
    op.create_foreign_key(None, 'problem_history', 'problem', ['problem_id'], ['problem_id'])
    op.create_table_comment(
        'problem_history',
        '문제 해결 히스토리 (bj_account 단위)',
        existing_comment='문제 해결 히스토리 (시간 정보 없음, streak과 연동)',
        schema=None
    )
    op.alter_column('system_log', 'system_log_id',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.create_table_comment(
        'user_date_record',
        '유저 단위 날짜별 풀이 수 기록 (streak 대체재)',
        existing_comment='유저+BJ계정 단위 날짜별 풀이 수 (streak 대체)',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'user_date_record',
        '유저+BJ계정 단위 날짜별 풀이 수 (streak 대체)',
        existing_comment='유저 단위 날짜별 풀이 수 기록 (streak 대체재)',
        schema=None
    )
    op.alter_column('system_log', 'system_log_id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.create_table_comment(
        'problem_history',
        '문제 해결 히스토리 (시간 정보 없음, streak과 연동)',
        existing_comment='문제 해결 히스토리 (bj_account 단위)',
        schema=None
    )
    op.drop_constraint(None, 'problem_history', type_='foreignkey')
    op.add_column('problem_date_record', sa.Column('user_account_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_pdr_user_account'), 'problem_date_record', 'user_account', ['user_account_id'], ['user_account_id'])
    op.create_table('problem_record',
    sa.Column('problem_record_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_account_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('problem_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('marked_date', sa.DATE(), nullable=True),
    sa.Column('solved_yn', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('memo_title', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=500), nullable=True),
    sa.Column('content', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=500), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.Column('order', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('representative_tag_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('banned_yn', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.problem_id'], name=op.f('problem_record_ibfk_1')),
    sa.ForeignKeyConstraint(['user_account_id'], ['user_account.user_account_id'], name=op.f('problem_record_ibfk_2')),
    sa.PrimaryKeyConstraint('problem_record_id'),
    comment='유저의 문제 기록',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='유저의 문제 기록',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('problem_banned_record',
    sa.Column('problem_banned_record_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('problem_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_account_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.problem_id'], name=op.f('problem_banned_record_ibfk_1')),
    sa.ForeignKeyConstraint(['user_account_id'], ['user_account.user_account_id'], name=op.f('problem_banned_record_ibfk_2')),
    sa.PrimaryKeyConstraint('problem_banned_record_id'),
    comment='유저의 문제 제외 기록',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='유저의 문제 제외 기록',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('will_solve_problem',
    sa.Column('will_solve_problem_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_account_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('problem_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('marked_date', sa.DATE(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.Column('solved', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('order', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.problem_id'], name=op.f('will_solve_problem_ibfk_1')),
    sa.ForeignKeyConstraint(['user_account_id'], ['user_account.user_account_id'], name=op.f('will_solve_problem_ibfk_2')),
    sa.PrimaryKeyConstraint('will_solve_problem_id'),
    comment='풀 문제 기록',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='풀 문제 기록',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
