"""db update

Revision ID: 6b55a22ff4f8
Revises: 84ae196aaec7
Create Date: 2026-01-02 08:21:05.606308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b55a22ff4f8'
down_revision: Union[str, Sequence[str], None] = '84ae196aaec7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('target',
    sa.Column('target_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('target_code', sa.String(length=50), nullable=False),
    sa.Column('active_yn', sa.Boolean(), nullable=False),
    sa.Column('target_display_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('target_id'),
    sa.UniqueConstraint('target_code', name='uk_target_code'),
    comment='목표 메타 정보'
    )
    op.create_table('tier',
    sa.Column('tier_id', sa.Integer(), nullable=False),
    sa.Column('tier_level', sa.Integer(), nullable=False),
    sa.Column('tier_code', sa.String(length=50), nullable=False),
    sa.Column('tier_rating', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('tier_id'),
    sa.UniqueConstraint('tier_level', 'tier_code', name='uk_tier_level_code'),
    comment='티어 메타 정보'
    )
    op.create_table('user_account',
    sa.Column('user_account_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.Enum('KAKAO', 'NAVER', 'GOOGLE', 'NONE', name='providerenum'), nullable=False),
    sa.Column('provider_id', sa.String(length=255), nullable=True),
    sa.Column('profile_image', sa.String(length=500), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_account_id'),
    comment='유저 계정'
    )
    op.create_index('idx_provider_id', 'user_account', ['provider', 'provider_id'], unique=False)
    op.create_table('bj_account',
    sa.Column('bj_account_id', sa.String(length=50), nullable=False),
    sa.Column('tier_start_date', sa.Date(), nullable=True),
    sa.Column('tier_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('contribution_count', sa.Integer(), nullable=False),
    sa.Column('class', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tier_id'], ['tier.tier_id'], ),
    sa.PrimaryKeyConstraint('bj_account_id'),
    comment='백준 계정'
    )
    op.create_table('problem',
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('problem_title', sa.String(length=500), nullable=False),
    sa.Column('problem_tier_level', sa.Integer(), nullable=False),
    sa.Column('class_level', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['problem_tier_level'], ['tier.tier_id'], ),
    sa.PrimaryKeyConstraint('problem_id'),
    comment='문제 메타 정보'
    )
    op.create_index('idx_problem_tier_level', 'problem', ['problem_tier_level'], unique=False)
    op.create_table('tag',
    sa.Column('tag_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tag_code', sa.String(length=100), nullable=False),
    sa.Column('tag_level', sa.String(length=50), nullable=False, comment='NEWBIE, BEGINNER, REQUIREMENT, DETAIL, CHALLENGE'),
    sa.Column('excluded_yn', sa.Boolean(), nullable=False),
    sa.Column('excluded_reason', sa.String(length=50), nullable=True, comment='INSIGNIFICANT, COMPREHENSIVE, MINOR'),
    sa.Column('min_problem_tier_id', sa.Integer(), nullable=True),
    sa.Column('max_problem_tier_id', sa.Integer(), nullable=True),
    sa.Column('min_solved_person_count', sa.Integer(), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=True),
    sa.Column('tag_problem_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['max_problem_tier_id'], ['tier.tier_id'], ),
    sa.ForeignKeyConstraint(['min_problem_tier_id'], ['tier.tier_id'], ),
    sa.PrimaryKeyConstraint('tag_id'),
    sa.UniqueConstraint('tag_code', name='uk_tag_code'),
    comment='태그'
    )
    op.create_table('tag_skill',
    sa.Column('tag_skill_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tag_level', sa.String(length=50), nullable=False, comment='NEWBIE, BEGINNER, REQUIREMENT, DETAIL, CHALLENGE'),
    sa.Column('tag_skill_code', sa.String(length=50), nullable=False, comment='IM, AD, MAS'),
    sa.Column('min_solved_problem', sa.Integer(), nullable=False),
    sa.Column('min_user_tier', sa.Integer(), nullable=False),
    sa.Column('min_solved_problem_tier', sa.Integer(), nullable=False),
    sa.Column('active_yn', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['min_solved_problem_tier'], ['tier.tier_id'], ),
    sa.ForeignKeyConstraint(['min_user_tier'], ['tier.tier_id'], ),
    sa.PrimaryKeyConstraint('tag_skill_id'),
    sa.UniqueConstraint('tag_level', 'tag_skill_code', name='uk_tag_skill'),
    comment='태그 숙련도'
    )
    op.create_table('user_target',
    sa.Column('user_target_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_account_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['target_id'], ['target.target_id'], ),
    sa.ForeignKeyConstraint(['user_account_id'], ['user_account.user_account_id'], ),
    sa.PrimaryKeyConstraint('user_target_id'),
    sa.UniqueConstraint('user_account_id', 'target_id', 'deleted_at', name='uk_user_target'),
    comment='유저 목표'
    )
    op.create_table('account_link',
    sa.Column('account_link_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_account_id', sa.Integer(), nullable=False),
    sa.Column('bj_account_id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bj_account_id'], ['bj_account.bj_account_id'], ),
    sa.ForeignKeyConstraint(['user_account_id'], ['user_account.user_account_id'], ),
    sa.PrimaryKeyConstraint('account_link_id'),
    sa.UniqueConstraint('user_account_id', 'bj_account_id', name='uk_user_bj_account'),
    comment='백준, 유저 계정 간 연동'
    )
    op.create_table('problem_banned_record',
    sa.Column('problem_banned_record_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('user_account_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.problem_id'], ),
    sa.ForeignKeyConstraint(['user_account_id'], ['user_account.user_account_id'], ),
    sa.PrimaryKeyConstraint('problem_banned_record_id'),
    comment='유저의 문제 제외 기록'
    )
    op.create_table('problem_history',
    sa.Column('problem_history_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bj_account_id', sa.String(length=50), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('solved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bj_account_id'], ['bj_account.bj_account_id'], ),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.problem_id'], ),
    sa.PrimaryKeyConstraint('problem_history_id'),
    comment='문제 해결 히스토리'
    )
    op.create_index('idx_solved_at', 'problem_history', ['solved_at'], unique=False)
    op.create_table('problem_recommendation_level_filter',
    sa.Column('filter_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filter_code', sa.String(length=50), nullable=False, comment='EASY, NORMAL, HARD, EXTREME'),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('max_user_tier_diff', sa.Integer(), nullable=True),
    sa.Column('min_user_tier_diff', sa.Integer(), nullable=True),
    sa.Column('tag_skill_id', sa.Integer(), nullable=False),
    sa.Column('tag_skill_rate', sa.Integer(), nullable=False),
    sa.Column('active_yn', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tag_skill_id'], ['tag_skill.tag_skill_id'], ),
    sa.PrimaryKeyConstraint('filter_id'),
    sa.UniqueConstraint('filter_code', name='uk_filter_code'),
    comment='문제 추천 난이도 필터 설정'
    )
    op.create_table('problem_record',
    sa.Column('problem_record_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_account_id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('marked_date', sa.Date(), nullable=True),
    sa.Column('solved_yn', sa.Boolean(), nullable=False),
    sa.Column('memo_title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.problem_id'], ),
    sa.ForeignKeyConstraint(['user_account_id'], ['user_account.user_account_id'], ),
    sa.PrimaryKeyConstraint('problem_record_id'),
    comment='유저의 문제 기록'
    )
    op.create_index('idx_marked_date', 'problem_record', ['marked_date'], unique=False)
    op.create_table('problem_tag',
    sa.Column('problem_tag_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.problem_id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.tag_id'], ),
    sa.PrimaryKeyConstraint('problem_tag_id'),
    sa.UniqueConstraint('problem_id', 'tag_id', name='uk_problem_tag'),
    comment='문제-태그 매핑'
    )
    op.create_table('problem_update_history',
    sa.Column('problem_update_history_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('problem_update_log', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.problem_id'], ),
    sa.PrimaryKeyConstraint('problem_update_history_id'),
    comment='문제 변경 정보'
    )
    op.create_table('tag_custom',
    sa.Column('tag_custom_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_account_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('excluded_yn', sa.Boolean(), nullable=False),
    sa.Column('excluded_reason', sa.String(length=50), nullable=True, comment='INSIGNIFICANT, COMPREHENSIVE, MINOR'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.tag_id'], ),
    sa.ForeignKeyConstraint(['user_account_id'], ['user_account.user_account_id'], ),
    sa.PrimaryKeyConstraint('tag_custom_id'),
    sa.UniqueConstraint('user_account_id', 'tag_id', 'deleted_at', name='uk_user_tag'),
    comment='태그 커스텀'
    )
    op.create_table('tag_relation',
    sa.Column('tag_relation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('leading_tag_id', sa.Integer(), nullable=False),
    sa.Column('sub_tag_id', sa.Integer(), nullable=False),
    sa.Column('active_yn', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['leading_tag_id'], ['tag.tag_id'], ),
    sa.ForeignKeyConstraint(['sub_tag_id'], ['tag.tag_id'], ),
    sa.PrimaryKeyConstraint('tag_relation_id'),
    sa.UniqueConstraint('leading_tag_id', 'sub_tag_id', name='uk_tag_relation'),
    comment='태그 관계'
    )
    op.create_table('tag_skill_history',
    sa.Column('tag_skill_history_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bj_account_id', sa.String(length=50), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('prev_skill_id', sa.Integer(), nullable=True),
    sa.Column('changed_skill_id', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bj_account_id'], ['bj_account.bj_account_id'], ),
    sa.ForeignKeyConstraint(['changed_skill_id'], ['tag_skill.tag_skill_id'], ),
    sa.ForeignKeyConstraint(['prev_skill_id'], ['tag_skill.tag_skill_id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.tag_id'], ),
    sa.PrimaryKeyConstraint('tag_skill_history_id'),
    comment='태그 숙련도 변경 히스토리'
    )
    op.create_table('target_tag',
    sa.Column('target_tag_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('active_yn', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.tag_id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['target.target_id'], ),
    sa.PrimaryKeyConstraint('target_tag_id'),
    sa.UniqueConstraint('target_id', 'tag_id', name='uk_target_code'),
    comment='목표 별 태그'
    )
    op.create_table('tier_history',
    sa.Column('tier_history_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bj_account_id', sa.String(length=50), nullable=False),
    sa.Column('prev_tier_id', sa.Integer(), nullable=False),
    sa.Column('changed_tier_id', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bj_account_id'], ['bj_account.bj_account_id'], ),
    sa.ForeignKeyConstraint(['changed_tier_id'], ['tier.tier_id'], ),
    sa.ForeignKeyConstraint(['prev_tier_id'], ['tier.tier_id'], ),
    sa.PrimaryKeyConstraint('tier_history_id'),
    comment='티어 변경 히스토리'
    )
    op.create_table('will_solve_problem',
    sa.Column('will_solve_problem_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_account_id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('marked_yn', sa.Boolean(), nullable=False),
    sa.Column('marked_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.problem_id'], ),
    sa.ForeignKeyConstraint(['user_account_id'], ['user_account.user_account_id'], ),
    sa.PrimaryKeyConstraint('will_solve_problem_id'),
    comment='풀 문제 기록'
    )
    op.create_index('idx_marked_date', 'will_solve_problem', ['marked_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_marked_date', table_name='will_solve_problem')
    op.drop_table('will_solve_problem')
    op.drop_table('tier_history')
    op.drop_table('target_tag')
    op.drop_table('tag_skill_history')
    op.drop_table('tag_relation')
    op.drop_table('tag_custom')
    op.drop_table('problem_update_history')
    op.drop_table('problem_tag')
    op.drop_index('idx_marked_date', table_name='problem_record')
    op.drop_table('problem_record')
    op.drop_table('problem_recommendation_level_filter')
    op.drop_index('idx_solved_at', table_name='problem_history')
    op.drop_table('problem_history')
    op.drop_table('problem_banned_record')
    op.drop_table('account_link')
    op.drop_table('user_target')
    op.drop_table('tag_skill')
    op.drop_table('tag')
    op.drop_index('idx_problem_tier_level', table_name='problem')
    op.drop_table('problem')
    op.drop_table('bj_account')
    op.drop_index('idx_provider_id', table_name='user_account')
    op.drop_table('user_account')
    op.drop_table('tier')
    op.drop_table('target')
    # ### end Alembic commands ###
