"""add recommendation period

Revision ID: b270af27c31e
Revises: 823f1a9a2553
Create Date: 2026-01-12 23:48:22.266039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b270af27c31e'
down_revision: Union[str, Sequence[str], None] = '823f1a9a2553'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag_skill', sa.Column('recommendation_period', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag_skill', 'recommendation_period')
    # ### end Alembic commands ###
