"""filter alter

Revision ID: b477d1d9dbf2
Revises: f0749137f69a
Create Date: 2026-01-13 08:06:48.969568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b477d1d9dbf2'
down_revision: Union[str, Sequence[str], None] = 'f0749137f69a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('uk_filter_code'), table_name='problem_recommendation_level_filter')
    op.drop_table_comment(
        'problem_recommendation_level_filter',
        existing_comment='문제 추천 난이도 필터 설정',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'problem_recommendation_level_filter',
        '문제 추천 난이도 필터 설정',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('uk_filter_code'), 'problem_recommendation_level_filter', ['filter_code'], unique=True)
    # ### end Alembic commands ###
