"""initial timing alter

Revision ID: dc70cd732018
Revises: 558e1f5665c3
Create Date: 2026-01-13 12:42:46.319443

"""
import sys
import os
from typing import Sequence, Union
from pathlib import Path

from alembic import op
import sqlalchemy as sa

BASE_DIR = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(BASE_DIR))

from db_initializer import DBMigrator, get_db_url


# revision identifiers, used by Alembic.
revision: str = 'dc70cd732018'
down_revision: Union[str, Sequence[str], None] = '558e1f5665c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 인덱스는 이미 558e1f5665c3에서 생성되었으므로 건드리지 않음
    # op.drop_index(op.f('idx_bj_account_id'), table_name='account_link')
    # op.drop_index(op.f('idx_user_account_id'), table_name='account_link')
    # op.create_index(op.f('ix_account_link_bj_account_id'), 'account_link', ['bj_account_id'], unique=False)
    # op.create_index(op.f('ix_account_link_user_account_id'), 'account_link', ['user_account_id'], unique=False)

    DB_URL = get_db_url()
    engine = sa.create_engine(DB_URL)
    migrator = DBMigrator(engine)
    migrator.execute_init()
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 인덱스는 이미 존재하므로 건드리지 않음
    # op.drop_index(op.f('ix_account_link_user_account_id'), table_name='account_link')
    # op.drop_index(op.f('ix_account_link_bj_account_id'), table_name='account_link')
    # op.create_index(op.f('idx_user_account_id'), 'account_link', ['user_account_id'], unique=False)
    # op.create_index(op.f('idx_bj_account_id'), 'account_link', ['bj_account_id'], unique=False)

    DB_URL = get_db_url()
    engine = sa.create_engine(DB_URL)
    migrator = DBMigrator(engine)
    migrator.truncate_all_tables()
    # ### end Alembic commands ###
