"""index

Revision ID: de31c4b099c2
Revises: 5664adfd081c
Create Date: 2026-01-20 12:09:28.242681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de31c4b099c2'
down_revision: Union[str, Sequence[str], None] = '5664adfd081c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'account_link', 'bj_account', ['bj_account_id'], ['bj_account_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'account_link', type_='foreignkey')
    # ### end Alembic commands ###
