"""display name

Revision ID: e5b6ca7e3819
Revises: 381148d35f11
Create Date: 2026-01-02 09:46:39.256275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5b6ca7e3819'
down_revision: Union[str, Sequence[str], None] = '6b55a22ff4f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('tag_display_name', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'tag_display_name')
    # ### end Alembic commands ###
