"""filter alter

Revision ID: f0749137f69a
Revises: a4c2e8f9d1b3
Create Date: 2026-01-13 08:05:54.039227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f0749137f69a'
down_revision: Union[str, Sequence[str], None] = 'a4c2e8f9d1b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem_recommendation_level_filter', sa.Column('tag_skill_code', sa.String(length=50), nullable=False, comment='IM, AD, MAS'))
    op.add_column('problem_recommendation_level_filter', sa.Column('min_tag_skill_rate', sa.Integer(), nullable=True))
    op.add_column('problem_recommendation_level_filter', sa.Column('max_tag_skill_rate', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('problem_recommendation_level_filter_ibfk_1'), 'problem_recommendation_level_filter', type_='foreignkey')
    op.drop_column('problem_recommendation_level_filter', 'tag_skill_id')
    op.drop_column('problem_recommendation_level_filter', 'tag_skill_rate')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem_recommendation_level_filter', sa.Column('tag_skill_rate', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('problem_recommendation_level_filter', sa.Column('tag_skill_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('problem_recommendation_level_filter_ibfk_1'), 'problem_recommendation_level_filter', 'tag_skill', ['tag_skill_id'], ['tag_skill_id'])
    op.drop_column('problem_recommendation_level_filter', 'max_tag_skill_rate')
    op.drop_column('problem_recommendation_level_filter', 'min_tag_skill_rate')
    op.drop_column('problem_recommendation_level_filter', 'tag_skill_code')
    # ### end Alembic commands ###
