export const TIER_INFO = {
  0: { rating: 0, name: 'Unrated', num: '', textColor: 'text-tier-undefined', bgColor: 'bg-tier-undefined' },
  1: { rating: 30, name: 'Bronze', num: 'V', textColor: 'text-tier-bronze', bgColor: 'bg-tier-bronze' },
  2: { rating: 60, name: 'Bronze', num: 'IV', textColor: 'text-tier-bronze', bgColor: 'bg-tier-bronze' },
  3: { rating: 90, name: 'Bronze', num: 'III', textColor: 'text-tier-bronze', bgColor: 'bg-tier-bronze' },
  4: { rating: 120, name: 'Bronze', num: 'II', textColor: 'text-tier-bronze', bgColor: 'bg-tier-bronze' },
  5: { rating: 150, name: 'Bronze', num: 'I', textColor: 'text-tier-bronze', bgColor: 'bg-tier-bronze' },
  6: { rating: 200, name: 'Silver', num: 'V', textColor: 'text-tier-silver', bgColor: 'bg-tier-silver' },
  7: { rating: 300, name: 'Silver', num: 'IV', textColor: 'text-tier-silver', bgColor: 'bg-tier-silver' },
  8: { rating: 400, name: 'Silver', num: 'III', textColor: 'text-tier-silver', bgColor: 'bg-tier-silver' },
  9: { rating: 500, name: 'Silver', num: 'II', textColor: 'text-tier-silver', bgColor: 'bg-tier-silver' },
  10: { rating: 650, name: 'Silver', num: 'I', textColor: 'text-tier-silver', bgColor: 'bg-tier-silver' },
  11: { rating: 800, name: 'Gold', num: 'V', textColor: 'text-tier-gold', bgColor: 'bg-tier-gold' },
  12: { rating: 950, name: 'Gold', num: 'IV', textColor: 'text-tier-gold', bgColor: 'bg-tier-gold' },
  13: { rating: 1100, name: 'Gold', num: 'III', textColor: 'text-tier-gold', bgColor: 'bg-tier-gold' },
  14: { rating: 1250, name: 'Gold', num: 'II', textColor: 'text-tier-gold', bgColor: 'bg-tier-gold' },
  15: { rating: 1400, name: 'Gold', num: 'I', textColor: 'text-tier-gold', bgColor: 'bg-tier-gold' },
  16: { rating: 1600, name: 'Platinum', num: 'V', textColor: 'text-tier-platinum', bgColor: 'bg-tier-platinum' },
  17: { rating: 1750, name: 'Platinum', num: 'IV', textColor: 'text-tier-platinum', bgColor: 'bg-tier-platinum' },
  18: { rating: 1900, name: 'Platinum', num: 'III', textColor: 'text-tier-platinum', bgColor: 'bg-tier-platinum' },
  19: { rating: 2000, name: 'Platinum', num: 'II', textColor: 'text-tier-platinum', bgColor: 'bg-tier-platinum' },
  20: { rating: 2100, name: 'Platinum', num: 'I', textColor: 'text-tier-platinum', bgColor: 'bg-tier-platinum' },
  21: { rating: 2200, name: 'Diamond', num: 'V', textColor: 'text-tier-diamond', bgColor: 'bg-tier-diamond' },
  22: { rating: 2300, name: 'Diamond', num: 'IV', textColor: 'text-tier-diamond', bgColor: 'bg-tier-diamond' },
  23: { rating: 2400, name: 'Diamond', num: 'III', textColor: 'text-tier-diamond', bgColor: 'bg-tier-diamond' },
  24: { rating: 2500, name: 'Diamond', num: 'II', textColor: 'text-tier-diamond', bgColor: 'bg-tier-diamond' },
  25: { rating: 2600, name: 'Diamond', num: 'I', textColor: 'text-tier-diamond', bgColor: 'bg-tier-diamond' },
  26: { rating: 2700, name: 'Ruby', num: 'V', textColor: 'text-tier-ruby', bgColor: 'bg-tier-ruby' },
  27: { rating: 2800, name: 'Ruby', num: 'IV', textColor: 'text-tier-ruby', bgColor: 'bg-tier-ruby' },
  28: { rating: 2850, name: 'Ruby', num: 'III', textColor: 'text-tier-ruby', bgColor: 'bg-tier-ruby' },
  29: { rating: 2900, name: 'Ruby', num: 'II', textColor: 'text-tier-ruby', bgColor: 'bg-tier-ruby' },
  30: { rating: 2950, name: 'Ruby', num: 'I', textColor: 'text-tier-ruby', bgColor: 'bg-tier-ruby' },
  31: { rating: 3000, name: 'Master', num: '', textColor: 'text-tier-master', bgColor: 'bg-tier-master' },
} as const;

export const TIER_TO_NUM = {
  Unrated: 0,
  B5: 1,
  B4: 2,
  B3: 3,
  B2: 4,
  B1: 5,
  S5: 6,
  S4: 7,
  S3: 8,
  S2: 9,
  S1: 10,
  G5: 11,
  G4: 12,
  G3: 13,
  G2: 14,
  G1: 15,
  P5: 16,
  P4: 17,
  P3: 18,
  P2: 19,
  P1: 20,
  D5: 21,
  D4: 22,
  D3: 23,
  D2: 24,
  D1: 25,
  R5: 26,
  R4: 27,
  R3: 28,
  R2: 29,
  R1: 30,
  M1: 31,
} as const;

export type TierNumKey = keyof typeof TIER_INFO;
export type TierKey = keyof typeof TIER_TO_NUM;
