pipeline {
    agent { label 'build-node' }

    stages {
        stage('Build & Deploy Development') {
            when { 
                allOf {
                    expression { 
                        return env.GIT_BRANCH?.contains('develop') || env.BRANCH_NAME == 'develop'
                    }
                    anyOf {
                        changeset "backend/**"
                        triggeredBy 'UserCause'
                    }
                }
            }
            options { skipDefaultCheckout() }
            steps {
                // 여러 개의 변수를 한 번에 가져오기
                withCredentials([
                    string(credentialsId: 'PROJECTS_ROOT', variable: 'ROOT_PATH'),
                    file(credentialsId: 'chuchu-be-env', variable: 'ENV_FILE_PATH')
                ]) {
                    // 변수를 사용할 때는 "${ROOT_PATH}" 형식으로 사용합니다.
                    dir("${ROOT_PATH}/chuchu-tree-dev") {
                        checkout scm 
                        dir('backend') {
                            sh "cp ${ENV_FILE_PATH} .env"
                            sh 'docker-compose -f docker-compose.dev.yml up -d --build'
                            sh 'rm .env'
                        }
                    }
                }
            }
        }

        stage('Build & Deploy Production') {
            when { 
                allOf {
                    expression { 
                        return env.GIT_BRANCH?.contains('main') || env.BRANCH_NAME == 'main'
                    }
                }
            }
            options { skipDefaultCheckout() }
            steps {
                withCredentials([
                    string(credentialsId: 'PROJECTS_ROOT', variable: 'ROOT_PATH'),
                    file(credentialsId: 'chuchu-be-env', variable: 'ENV_FILE_PATH')
                ]) {
                    dir("${ROOT_PATH}/chuchu_tree") {
                        checkout scm 
                        dir('backend') {
                            sh "cp ${ENV_FILE_PATH} .env"
                            sh 'docker-compose -f docker-compose.prod.yml up -d --build'
                            sh 'rm .env'
                        }
                    }
                }
            }
        }
    }
}
