"""will solved problem add order

Revision ID: 36ad2838530f
Revises: 09b86e2a6522
Create Date: 2026-01-06 12:39:17.682294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '36ad2838530f'
down_revision: Union[str, Sequence[str], None] = '09b86e2a6522'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('will_solve_problem', sa.Column('solved', sa.Boolean(), nullable=False))
    op.add_column('will_solve_problem', sa.Column('order', sa.Integer(), nullable=False))
    op.drop_column('will_solve_problem', 'marked_yn')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('will_solve_problem', sa.Column('marked_yn', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_column('will_solve_problem', 'order')
    op.drop_column('will_solve_problem', 'solved')
    # ### end Alembic commands ###
