"""1000

Revision ID: 3f0a6a57a553
Revises: 4fedede14308
Create Date: 2026-02-07 14:11:55.630889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from db_initializer import DBMigrator, get_db_url

# revision identifiers, used by Alembic.
revision: str = '3f0a6a57a553'
down_revision: Union[str, Sequence[str], None] = '4fedede14308'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    DB_URL = get_db_url()
    engine = sa.create_engine(DB_URL)
    migrator = DBMigrator(engine)
    migrator.execute_init()
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    DB_URL = get_db_url()
    engine = sa.create_engine(DB_URL)
    migrator = DBMigrator(engine)
    migrator.truncate_all_tables()
    # ### end Alembic commands ###
