"""user_problem_status and presentative

Revision ID: 4fedede14308
Revises: de31c4b099c2
Create Date: 2026-01-23 17:42:27.133487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fedede14308'
down_revision: Union[str, Sequence[str], None] = 'de31c4b099c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_problem_status',
    sa.Column('user_problem_status_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_account_id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('banned_yn', sa.Boolean(), nullable=False),
    sa.Column('solved_yn', sa.Boolean(), nullable=False),
    sa.Column('representative_tag_id', sa.Integer(), nullable=True),
    sa.Column('memo_title', sa.String(length=500), nullable=True),
    sa.Column('content', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.problem_id'], ),
    sa.ForeignKeyConstraint(['user_account_id'], ['user_account.user_account_id'], ),
    sa.PrimaryKeyConstraint('user_problem_status_id'),
    sa.UniqueConstraint('user_account_id', 'problem_id', name='uk_user_problem'),
    comment='유저의 문제별 상태 (마스터)'
    )
    op.create_index('idx_user_status', 'user_problem_status', ['user_account_id', 'banned_yn', 'solved_yn'], unique=False)
    op.create_table('problem_date_record',
    sa.Column('problem_date_record_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_problem_status_id', sa.Integer(), nullable=False),
    sa.Column('marked_date', sa.Date(), nullable=False),
    sa.Column('record_type', sa.Enum('WILL_SOLVE', 'SOLVED', name='recordtype'), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_problem_status_id'], ['user_problem_status.user_problem_status_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('problem_date_record_id'),
    comment='날짜별 문제 기록 (디테일)'
    )
    op.create_index('idx_marked_date', 'problem_date_record', ['marked_date'], unique=False)
    op.create_index('idx_status_date', 'problem_date_record', ['user_problem_status_id', 'marked_date'], unique=False)
    op.add_column('problem_record', sa.Column('representative_tag_id', sa.Integer(), nullable=True))
    op.add_column('problem_record', sa.Column('banned_yn', sa.Boolean(), nullable=False))
    op.create_index('idx_user_status', 'problem_record', ['user_account_id', 'banned_yn', 'solved_yn'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_status', table_name='problem_record')
    op.drop_column('problem_record', 'banned_yn')
    op.drop_column('problem_record', 'representative_tag_id')
    op.drop_index('idx_status_date', table_name='problem_date_record')
    op.drop_index('idx_marked_date', table_name='problem_date_record')
    op.drop_table('problem_date_record')
    op.drop_index('idx_user_status', table_name='user_problem_status')
    op.drop_table('user_problem_status')
    # ### end Alembic commands ###
