"""github enum add

Revision ID: 823f1a9a2553
Revises: 41282e124456
Create Date: 2026-01-12 23:42:04.059096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '823f1a9a2553'
down_revision: Union[str, Sequence[str], None] = '41282e124456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem', sa.Column('solved_user_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problem', 'solved_user_count')
    # ### end Alembic commands ###
