export const TAG_INFO = {
  math: { kr: '수학', bgColor: 'bg-tag-blu-bg', textColor: 'text-tag-blu-text' },
  sorting: { kr: '정렬', bgColor: 'bg-tag-ora-bg', textColor: 'text-tag-ora-text' },
  geometry: { kr: '기하학', bgColor: 'bg-tag-yel-bg', textColor: 'text-tag-yel-text' },
  arithmetic: { kr: '사칙연산', bgColor: 'bg-tag-gre-bg', textColor: 'text-tag-gre-text' },
  number_theory: { kr: '정수론', bgColor: 'bg-tag-blu-bg', textColor: 'text-tag-blu-text' },
  combinatorics: { kr: '조합론', bgColor: 'bg-tag-pup-bg', textColor: 'text-tag-pup-text' },
  primality_test: { kr: '소수 판정', bgColor: 'bg-tag-red-bg', textColor: 'text-tag-red-text' },
  implementation: { kr: '구현', bgColor: 'bg-tag-gre-bg', textColor: 'text-tag-gre-text' },
  greedy: { kr: '그리디', bgColor: 'bg-tag-yel-bg', textColor: 'text-tag-yel-text' },
  string: { kr: '문자열', bgColor: 'bg-tag-gre-bg', textColor: 'text-tag-gre-text' },
  bruteforcing: { kr: '브루트포스', bgColor: 'bg-tag-blu-bg', textColor: 'text-tag-blu-text' },
  trees: { kr: '트리', bgColor: 'bg-tag-pup-bg', textColor: 'text-tag-pup-text' },
  set: { kr: '집합과 맵', bgColor: 'bg-tag-red-bg', textColor: 'text-tag-red-text' },
  simulation: { kr: '시뮬레이션', bgColor: 'bg-tag-ora-bg', textColor: 'text-tag-ora-text' },
  prefix_sum: { kr: '누적합', bgColor: 'bg-tag-yel-bg', textColor: 'text-tag-yel-text' },
  bfs: { kr: '너비 우선 탐색', bgColor: 'bg-tag-gre-bg', textColor: 'text-tag-gre-text' },
  dfs: { kr: '깊이 우선 탐색', bgColor: 'bg-tag-blu-bg', textColor: 'text-tag-blu-text' },
  hash_set: { kr: '해시맵', bgColor: 'bg-tag-pup-bg', textColor: 'text-tag-pup-text' },
  backtracking: { kr: '백트래킹', bgColor: 'bg-tag-red-bg', textColor: 'text-tag-red-text' },
  stack: { kr: '스택', bgColor: 'bg-tag-ora-bg', textColor: 'text-tag-ora-text' },
  recursion: { kr: '재귀', bgColor: 'bg-tag-yel-bg', textColor: 'text-tag-yel-text' },
  arbitrary_precision: { kr: '큰 수 연산', bgColor: 'bg-tag-gre-bg', textColor: 'text-tag-gre-text' },
  sieve: { kr: '에라토스테네스의 체', bgColor: 'bg-tag-blu-bg', textColor: 'text-tag-blu-text' },
  deque: { kr: '덱', bgColor: 'bg-tag-pup-bg', textColor: 'text-tag-pup-text' },
  queue: { kr: '큐', bgColor: 'bg-tag-red-bg', textColor: 'text-tag-red-text' },
  dp: { kr: '다이나믹 프로그래밍', bgColor: 'bg-tag-ora-bg', textColor: 'text-tag-ora-text' },
  ad_hoc: { kr: '애드 혹', bgColor: 'bg-tag-yel-bg', textColor: 'text-tag-yel-text' },
  binary_search: { kr: '이분 탐색', bgColor: 'bg-tag-gre-bg', textColor: 'text-tag-gre-text' },
  shortest_path: { kr: '최단 경로', bgColor: 'bg-tag-blu-bg', textColor: 'text-tag-blu-text' },
  bitmask: { kr: '비트마스킹', bgColor: 'bg-tag-pup-bg', textColor: 'text-tag-pup-text' },
  disjoint_set: { kr: '분리 집합', bgColor: 'bg-tag-red-bg', textColor: 'text-tag-red-text' },
  tree_set: { kr: '트리맵', bgColor: 'bg-tag-ora-bg', textColor: 'text-tag-ora-text' },
  priority_queue: { kr: '우선순위 큐', bgColor: 'bg-tag-yel-bg', textColor: 'text-tag-yel-text' },
  divide_and_conquer: { kr: '분할 정복', bgColor: 'bg-tag-gre-bg', textColor: 'text-tag-gre-text' },
  two_pointer: { kr: '투 포인터', bgColor: 'bg-tag-blu-bg', textColor: 'text-tag-blu-text' },
  euclidean: { kr: '유클리드 호제법', bgColor: 'bg-tag-pup-bg', textColor: 'text-tag-pup-text' },
  grid_graph: { kr: '격자 그래프', bgColor: 'bg-tag-red-bg', textColor: 'text-tag-red-text' },
  sliding_window: { kr: '슬라이딩 윈도우', bgColor: 'bg-tag-ora-bg', textColor: 'text-tag-ora-text' },
  segtree: { kr: '세그먼트 트리', bgColor: 'bg-tag-yel-bg', textColor: 'text-tag-yel-text' },
  dijkstra: { kr: '데이크스트라', bgColor: 'bg-tag-gre-bg', textColor: 'text-tag-gre-text' },
  dp_tree: { kr: '트리 DP', bgColor: 'bg-tag-blu-bg', textColor: 'text-tag-blu-text' },
  lazyprop: { kr: 'Lazy 세그먼트 트리', bgColor: 'bg-tag-pup-bg', textColor: 'text-tag-pup-text' },
  flow: { kr: '최대 유량', bgColor: 'bg-tag-red-bg', textColor: 'text-tag-red-text' },
  dp_bitfield: { kr: '비트 DP', bgColor: 'bg-tag-ora-bg', textColor: 'text-tag-ora-text' },
  knapsack: { kr: '배낭 문제', bgColor: 'bg-tag-yel-bg', textColor: 'text-tag-yel-text' },
  mst: { kr: '최소 스패닝 트리', bgColor: 'bg-tag-gre-bg', textColor: 'text-tag-gre-text' },
  topological_sorting: { kr: '위상 정렬', bgColor: 'bg-tag-blu-bg', textColor: 'text-tag-blu-text' },
  lca: { kr: '최소 공통 조상', bgColor: 'bg-tag-pup-bg', textColor: 'text-tag-pup-text' },
  floyd_warshall: { kr: '플로이드-워셜', bgColor: 'bg-tag-red-bg', textColor: 'text-tag-red-text' },
  traceback: { kr: '역추적', bgColor: 'bg-tag-ora-bg', textColor: 'text-tag-ora-text' },
  trie: { kr: '트라이', bgColor: 'bg-tag-yel-bg', textColor: 'text-tag-yel-text' },
  lis: { kr: '최장 증가 부분 수열', bgColor: 'bg-tag-gre-bg', textColor: 'text-tag-gre-text' },
  mcmf: { kr: '최소 비용 최대 유량', bgColor: 'bg-tag-blu-bg', textColor: 'text-tag-blu-text' },
  kmp: { kr: 'KMP', bgColor: 'bg-tag-pup-bg', textColor: 'text-tag-pup-text' },
  tsp: { kr: '외판원 순회', bgColor: 'bg-tag-red-bg', textColor: 'text-tag-red-text' },
  bipartite_matching: { kr: '이분 매칭', bgColor: 'bg-tag-ora-bg', textColor: 'text-tag-ora-text' },
  scc: { kr: '강한 연결 요소', bgColor: 'bg-tag-yel-bg', textColor: 'text-tag-yel-text' },
  convex_hull: { kr: '볼록 껍질', bgColor: 'bg-tag-gre-bg', textColor: 'text-tag-gre-text' },
};

export type CategoryName = 'INTERMEDIATE' | 'ADVANCED' | 'MASTER' | 'EXCLUDED' | 'LOCKED';

export type TargetCode = 'DAILY' | 'BEGINNER' | 'CT';

export type TagKey = keyof typeof TAG_INFO;
